### PR TITLE
Split /utils into( /gtp, /options), and /test/utils ( /test/base_server_packets, /test/fake_modules, /test/module_loading, /test/utils)

### PR DESCRIPTION
**Pull request by wonderingabout**

### CODE REVIEW

**Comment by Dorus** [comment]
This can be merged @roy7

**Comment by wonderingabout** [comment]
i also added /gtp/** and /options/** to files list for npm install

**Comment by roy7** [comment]
So don't merge this one quite yet per discussion in #341?

**Comment by wonderingabout** [comment]
> So don't merge this one quite yet per discussion in #341?

#341 should be merged first or closed before merging this pr

@Dorus thought it may be redundant to merge #341 before this one since we already fix the issue in #342 , and i thought it's cool to have a pr that specifically fixes an important issue instead of wrapping everything in one pr

in all cases result will be the same, problem will be fixed, so whichever way is fine, just we need to decide on #341 first before dealing with #342

**Comment by wonderingabout** [comment]
actually this can be merged immediately, and after that i need to pull latest devel to #340 and fix it

**Comment by Dorus** [comment]
@roy7 No the discussion was to close #341 (that has happened now), this one should be merged.

**Pull request merged**
