### PR TITLE
fix

### PR DESCRIPTION
**Pull request by wonderingabout**

### CODE REVIEW

**Comment by Dorus** [comment]
We should really add a test on this stuff.

**Comment by Dorus** [comment]
This is not good. I used ``--rankedonly  and I send an unranked challange and i get the error:
`Ranked games are not allowed on this bot.`

**Comment by Dorus** [comment]
I manually tested it. All good now. Anyway we can merge this asap @roy7.

**Comment by wonderingabout** [comment]
> I manually tested it. All good now. Anyway we can merge this asap @roy7.

recently i'm starting to miss github messages and sometimes see them but dont get the drive to immediately reply to them until i forget, sorry about that @Dorus , will pay more attention about that in the future :+1: 
ty for your reviews as always, hope i can learn more and more :)

**Comment by Dorus** [comment]
Haha dont beat yourelf up over it @wonderingabout, we're moving at amazing speed here :)

**Comment by wonderingabout** [comment]
> Haha dont beat yourelf up over it @wonderingabout, we're moving at amazing speed here :)

ty @Dorus , i'm very glad to be able to dev with you and @roy7 !!!

**Pull request merged**
