### PR TITLE
Function genericallowedfamilies reject

### PR DESCRIPTION
**Pull request by wonderingabout**
@roy7 @Dorus @windo 

this PR is on top of #178 

read commit message for details
didnt test it, but i hope it works :+1:

### CODE REVIEW

**Comment by wonderingabout** [comment]
should be final version and work now :+1: 

(still didnt test it though)

**Comment by wonderingabout** [comment]
as expected :smile:

**Comment by wonderingabout** [comment]
update : this code was quite cool, but since i couldnt find how to easily extract name from an object property, adding an extra parameter to main function instead

bye, my old code below : 

```
function pluralAllowedFamilyArgToSingularString(toConvert) { /* {{{ */
    let converted = String(toConvert)                // for example String(config.speedsranked)
                    .split("config.")[1]             // for example : "speedsranked"
                    .split("unranked")[0]            // for example : "speedsranked"
                    .split("ranked")[0];             // for example : "speeds"
    converted = (Array.from(converted));             // for example ["s", "p", "e", "e", "d", "s"]
    converted.pop();                                 // for example ["s", "p", "e", "e", "d"]
    converted = converted.join("");                  // for example "speed"
    return converted;
} /* }}} */
```

**Comment by wonderingabout** [comment]
@roy7 @Dorus @windo 

just rebased and fixed
didnt test the ogs code, but tested the function plural to singular to work :+1:

**Comment by wonderingabout** [comment]
this test fail may be a good hint to stop using these aliases 

```
        let t = notification.time_control;
        let user = notification.user;
```

looking at gtp2ogs code, are used only in connection.js in 2 functions only, and all other parts of the code never use it

so it may make our code more solid

if its ok with you, i can push an all in one commit to remove it @Dorus @roy7 @windo @anoek

**Comment by roy7** [comment]
The test fail was just missing a comma, nothing to do with the alias. :)

**Comment by wonderingabout** [comment]
yes, ty @roy7 fixed now :+1: 

but now that we mentionned it, i still think it may be good to remove the `let user = notification.user` alias, but we can review that another time :+1:

**Pull request merged**
