### PR TITLE
intuitive semi-syllabic aliases + readme wrap + readme clearer + renamed any -> all komi/boardsize + renamed maxrankedhandicap -> maxhandicapranked + max/minmaintimeranked/unranked + max/minperiodtimeranked/unranked + noautohandicap All in one commit (AiO version)

### PR DESCRIPTION
**Pull request by wonderingabout**
so !

A few more interesting changes :+1: 

general look here : https://github.com/wonderingabout/gtp2ogs/tree/intuitive_semi_syllabic_aliases-readmewrap-noautohandicap-maxmaintimeranked-maxperiodtimeranked-maxhandicapranked-anyallkomiboardsize

- added many aliases as well with the new **"intuitive semi-syllabic aliases"** system !!! :1st_place_medal: 
- added `--logfile` on readme
- added alias `--l` for it
- word wrap on readme.md and contributing.md , amazing isnt it !!! @roy7 , unbelievable !!  :open_mouth:
- renamed `any` to `all` : it is more intuitive to allow ALL komi values and ALL board sizes (if you notice, the word "any" is used in a different meaning in the readme notes for komi explanation, so in itself is confusing) @windo do you think its a good idea ?
- renamed `maxrankedhandicap` to `maxhandicapranked` for consistency with `nopauseranked` `banranked` `minperiodsranked` `maxhandicap`
- added `--noautohandicap` (default is false) to avoid bypass min-max handicap limit , with `--nah` alias , and also `--noautohandicapranked` and `--noautohandicapunranked` or `--nahr` and `--nahu`
- added `--maxmaintimeranked` `--maxperiodtimeranked` and their min + unranked combinations in aliases, some bot admins will sure find useful to set short time for ranked games : `--1mtr 300 --1pr 5 --1ptr 30`
- made the discord chat more obvious, but also adding an explanation that "issues" should be used rather for long problems
- short explanation about being a bot admin
- renamed contributing-readme.md to contributing.md (that was the initial plan, forgot about it)
- a few minor other changes

noautohandicap

has been tested to work and ready to merge @roy7 :100: 
continutation of the fat #103

### CODE REVIEW

**Comment by roy7** [comment]
@windo Will merging this set you back on #99?

**Comment by windo** [comment]
I don't mind rebasing, no worries about merging this. Using `any` vs `all` as the `--komi` option SGTM. 

With renaming arguments (and values), does optimist just silently ignore arguments it does not know about? Maybe the number of users is small enough that it does not matter, but as a general "best practice" for updating an interface like this is to:

1. Add support for the new options but keep accepting the old options too. They could be accepted as aliases, be undocumented and hidden when `--help` is called and cause a warning message to be logged when used to make sure users stop using them. That is, both `--maxrankedhandicap` and `--maxhandicapranked` would work but `--maxhandicapranked` would not be advertised anywhere and would complain (or possibly even not start at all) when used. Give all users that update the chance to notice they are using the old options and update their usage.
2. In a second change, some time later, remove the old options.

Alternatively, at least we should make sure anyone updating gtp2ogs will know that they will need to change the command lines they use after this update. I personally would not read all the commit messages after every pull request so I don't know if we have any way of doing that reliably.

**Comment by wonderingabout** [comment]
@windo 

these good practices sure are wise :+1: 

but as you said the userbase of gtp2ogs is very small (at peak we have 10 bots playable on "computer" list)
i can message all bot accounts and their bot admins on ogs to notify them of the change in gtp2ogs

and another reason why i think its not needed is that actually most people never update their gtp2ogs, as long as it works for them they mostly just keep their old version

but i'll still message them all on ogs, so i think we can go ahead and delete the old feature in one run, less maintainance like that :+1: 

also, 

> but --maxhandicapranked would not be advertised anywhere 

its the old `--maxrankedhandicap` that gets deleted, to use the same format as all other "ranked" arguments : `--maxhandicapranked` `--maxperiodsranked` `--nopauseranked` `--maxmaintimeranked` `--maxperiodtimeranked` 
and their ISSA : `--1hr` `--1pr` `--npr` `--1mtr` `--1ptr`

good :+1:

**Comment by wonderingabout** [comment]
also sorry to make you base and rebase btw :+1: 

(i'm currently working on a time converter for reject messages, instead of "min time = 600 seconds" it will convert in human readable time (+/x days +/-y hours +/-x minutes z seconds), the math for it is already written, i'm incorporating it in a function, should be ready in a few days i hope :+1:

**Comment by windo** [comment]
Are you using something like [human-duration](https://www.npmjs.com/package/human-duration) for that?

**Comment by wonderingabout** [comment]
@windo 

i dont know, i'm learning to code in javascript, so with the little skills i'm learning i'm now able to code a little :smile: 

i wrote the math and strings for it, but i'm studying the "functions" chapter now :+1: 

still unfinished, but this is my code so far : 

```
        /////////////////////////////////////////////////////
        /////// time converter for reject messages !!! //////
        /////////////////////////////////////////////////////

        let botSecondsTime = Number("0"); // time in seconds, for example 600 seconds
        function hrt(botSecondsTime) {    // hrt is human readable time

            // < 60 seconds is < 1 minute -> "z0 seconds"
            if (botSecondsTime< 60) {
                return `${botSecondsTime} seconds`;
                

            // < 3600 seconds is < 1 hour -> "y1 minutes z1 seconds"
            } else if ((botSecondsTime < 3600) && (botSecondsTime>= 60)) {
                return `${Math.trunc(botSecondsTime / 60)} minutes ${(botSecondsTime % 60)} seconds`;
                

            // < 86400 seconds is < 1 day -> "x2 hours y2 minutes z2 seconds"
            } else if ((botSecondsTime < 86400) && (botSecondsTime >= 3600)) {
                return `${Math.trunc(botSecondsTime / 3600)} hours ${((Math.trunc(botSecondsTime / 60) % 60)} minutes ${(botSecondsTime % 60)} seconds`;
                

            // < 2592000 seconds = 30 days is < 1 month -> "w3 days x3 hours y3 minutes z3 seconds"
            } else if ((botSecondsTime< 2592000) && (botSecondsTime >= 86400)) {
                return `${Math.trunc(botSecondsTime / 86400)} days ${(Math.trunc(botSecondsTime / 3600) % 24))} hours ${(Math.trunc(botSecondsTime / 60) % 60)} minutes ${(botSeconds % 60)} seconds`;
                

            // in case time is higher than 1 month, or in some other unknown case, 
            // return value in seconds
            // currently longest time setting on ogs is 28 days for correspondence games,  
            // update this if there are time changes on ogs in the future

            } else { 
                return `${botSecondsTime} seconds (bigger than 30 days`);

            }
        }

        /////////////////////////////////////////////////////
        ////////// **** end of time converter **** //////////
        /////////////////////////////////////////////////////
```

i wanted to keep the surprise, but i guess its time to share it unfinished now lol

**Comment by roy7** [comment]
Ok I'll merge this in. Once we're sure nothing breaks from @windo or other active bot admins, I think it'll be time to move this all out of devel and into master. Then we'll merge in the bigger changes to split into multiple files/etc into a fresh devel.

@wonderingabout The NPM package he mentioned seems to do exactly what you want https://www.npmjs.com/package/human-duration

@Dorus Do you want to merge in your split2 usage cleaner error logging before we update master?

**Comment by wonderingabout** [comment]
oh @roy7 

didnt read it yet, i was having fun writing it

its unfinished but i went with a new universal method :1st_place_medal: 

also, since its only for reject messages, i thought maybe the code i'm writing can be useful :)

look at my new code @windo @roy7 (unfinished since its a new version) : 

```
                let s0 =
                let m1 =
                let s1 =
                let h2 =
                let m2 =
                let s2 =
                let d3 = Math.trunc(botSecondsTime / 86400); /*days*/
                let h3 = Math.trunc(botSecondsTime / 3600) % 24; /*hours*/
                let m3 = Math.trunc(botSecondsTime / 60) % 60; /*minutes*/
                let s3 = botSeconds % 60; /*seconds*/
                dd = d3;
                hh = h3;
                mm = m3;
                ss = s3;
 
                if (dd===0) {
                // dont display 0 in 0 days ...

                    if (hh===0) { 
                    // dont display 0 in 0 days 0 hours ...
                        if (mm===0) {
                        // dont display 0 in 0 days 0 hours 0 minutes ...
                            if (ss===0) {
                            // dont display 0 in 0 days 0 hours 0 minutes, but display 0 seconds
                            return `${ss} seconds`;
                            } else {
                            // dont display 0 in 0 days 0 hours 0 minutes ss seconds
                            return `${ss} seconds`;
                            }
                        } else {
                        // dont display 0 in 0 days 0 hours mm minutes ...
                            if (ss===0) {
                            // dont display 0 in 0 days 0 hours mm minutes 0 seconds
                            return `${mm} minutes`;
                            } else {
                            // dont display 0 in 0 days 0 hours mm minutes ss seconds
                            return `${mm} minutes ${ss} seconds`;
                            }
                        }    
                    } else {
                    // dont display 0 in 0 days hh hours ...
                        if (mm===0) {
                        // dont display 0 in 0 days hh hours 0 minutes ...
                            if (ss===0) {
                            // dont display 0 in 0 days hh hours 0 minutes 0 seconds
                            return `${hh} hours`;
                            } else {
                            // dont display 0 in 0 days hh hours 0 minutes ss seconds
                            return `${hh} hours ${ss} seconds`;
                            }
                        } else {
                        // dont display 0 in 0 days hh hours mm minutes ...
                            if (ss===0) {
                            // dont display 0 in 0 days hh hours mm minutes 0 seconds
                            return `${hh} hours ${mm} minutes`;
                            } else {
                            // dont display 0 in 0 days hh hours mm minutes ss seconds
                            return `${hh} hours ${mm} minutes ${ss} seconds`;
                            }
                        }
                    }
                } else { 
                // dont display 0 in dd days ... 

```

**Comment by wonderingabout** [comment]
and as usual ty for the merge @roy7 :1st_place_medal:

**Comment by wonderingabout** [comment]
```
        /////////////////////////////////////////////////////////
        /////// !!! time converter for reject messages !!! //////
        /////////////////////////////////////////////////////////
        
            // 1) currently days is the biggest time unit on ogs (max is 28 days), 
            // so not using a modulo 30 at day number
            // for example 38 days will not be displayed as 1 month + 8 days
            // but instead as 38 days
            // 2) however this time converter includes the architecture 
            // if needed to upscale it in future releases,
            // but since it's unlikely atm keeping it simple

            let botSecondsTime = Number("0"); // time in seconds, for example 600 seconds
            function hrt(botSecondsTime) {

                // let MM = (Math.trunc(botSecondsTime / 2592000);  /*months without modulo 12, currently empty*/
                let dd = (Math.trunc(botSecondsTime / 86400)); /*days, without modulo 30 atm*/
                let hh = (Math.trunc(botSecondsTime / 3600) % 24); /*hours*/
                let mm = (Math.trunc(botSecondsTime / 60) % 60); /*minutes*/
                let ss = (botSeconds % 60); /*seconds*/

                // if (MM===0) {
                // dont display 0 in 0 months ...
 
                    if (dd===0) {
                    // dont display 0 in 0 months 0 days ...

                        if (hh===0) { 
                        // dont display 0 in 0 months 0 days 0 hours ...
                            if (mm===0) {
                            // dont display 0 in 0 months 0 days 0 hours 0 minutes ...
                                if (ss===0) {
                                // dont display 0 in 0 months 0 days 0 hours 0 minutes, but display 0 seconds
                                return `${ss} seconds`;
                                } else {
                                // dont display 0 in 0 months 0 days 0 hours 0 minutes ss seconds
                                return `${ss} seconds`;
                                }
                            } else {
                            // dont display 0 in 0 months 0 days 0 hours mm minutes ...
                                if (ss===0) {
                                // dont display 0 in 0 months 0 days 0 hours mm minutes 0 seconds
                                return `${mm} minutes`;
                                } else {
                                // dont display 0 in 0 months 0 days 0 hours mm minutes ss seconds
                                return `${mm} minutes ${ss} seconds`;
                                }
                            }    
                        } else {
                        // dont display 0 in 0 months 0 days hh hours ...
                            if (mm===0) {
                            // dont display 0 in 0 months 0 days hh hours 0 minutes ...
                                if (ss===0) {
                                // dont display 0 in 0 months 0 days hh hours 0 minutes 0 seconds
                                return `${hh} hours`;
                                } else {
                                // dont display 0 in 0 months 0 days hh hours 0 minutes ss seconds
                                return `${hh} hours ${ss} seconds`;
                                }
                            } else {
                            // dont display 0 in 0 months 0 days hh hours mm minutes ...
                                if (ss===0) {
                                // dont display 0 in 0 months 0 days hh hours mm minutes 0 seconds
                                return `${hh} hours ${mm} minutes`;
                                } else {
                                // dont display 0 in 0 months 0 days hh hours mm minutes ss seconds
                                return `${hh} hours ${mm} minutes ${ss} seconds`;
                                }
                            }
                        }

                    } else if (dd>=1) { 
                    // dont display 0 in dd days ...

                        if (hh===0) { 
                        // dont display 0 in 0 months dd days 0 hours ...
                            if (mm===0) {
                            // dont display 0 in 0 months dd days 0 hours 0 minutes ...
                                if (ss===0) {
                                // dont display 0 in 0 months dd days 0 hours 0 minutes
                                return `${dd} days`;
                                } else {
                                // dont display 0 in 0 months dd days 0 hours 0 minutes ss seconds
                                return `${dd} days ${ss} seconds`;
                                }
                            } else {
                            // dont display 0 in 0 months dd days 0 hours mm minutes ...
                                if (ss===0) {
                                // dont display 0 in 0 months dd days 0 hours mm minutes 0 seconds
                                return `${dd} days ${mm} minutes`;
                                } else {
                                // dont display 0 in 0 months dd days 0 hours mm minutes ss seconds
                                return `${days} days ${mm} minutes ${ss} seconds`;
                                }
                            }    
                        } else {
                        // dont display 0 in 0 months dd days hh hours ...
                            if (mm===0) {
                            // dont display 0 in 0 months dd days hh hours 0 minutes ...
                                if (ss===0) {
                                // dont display 0 in 0 months dd days hh hours 0 minutes 0 seconds
                                return `${dd} days ${hh} hours`;
                                } else {
                                // dont display 0 in 0 months dd days hh hours 0 minutes ss seconds
                                return `${dd} days ${hh} hours ${ss} seconds`;
                                }
                            } else {
                            // dont display 0 in 0 months dd days hh hours mm minutes ...
                                if (ss===0) {
                                // dont display 0 in 0 months dd days hh hours mm minutes 0 seconds
                                return `${dd} days ${hh} hours ${mm} minutes`;
                                } else {
                                // dont display 0 in 0 months dd days hh hours mm minutes ss seconds
                                return `${dd} days ${hh} hours ${mm} minutes ${ss} seconds`;
                                }
                            }
                         }
                     }

                    } else {
                    // error, something went wrong, 
                        return `error, something went wrong, ${botSecondsTime} seconds is not an understood value`;
                    }

        /////////////////////////////////////////////////////
        ////////// **** end of time converter **** //////////
        /////////////////////////////////////////////////////
```

**Comment by Dorus** [comment]
I would have kept it shorter:
```Js
function hrt(time) {
  let ss = time % 60;
  let mm = Math.floor(time / 60 % 60);
  let hh = Math.floor(time / (60*60) % 24);
  let dd = Math.floor(time / (60*60*24));
  let text = ["days", "hours", "minutes", "seconds"];
  return [dd, hh, mm, ss].map((e, i) => e === 0 ? "" : `${e} ${text[i]}`)
    .filter(e => e !== "")
    .join(" ");
}
```

**Comment by wonderingabout** [comment]
@windo see : https://github.com/online-go/gtp2ogs/pull/110

**Pull request merged**
