### PR TITLE
eslint: enable recommended rules

### PR DESCRIPTION
**Pull request by windo**
I had expected this to be harder for some reason but it was really just
a few tweaks to appease the default linter options:

  * Remove some semicolons
  * Remove some unused variables, arguments and functions
  * Replace an undefined dup() invocation

### CODE REVIEW

**Comment by windo** [comment]
@wonderingabout - LMK what do you think should be done `universalMaintime` and `universalPeriodtime` from ec822665 - it seems they are unused so the linter requests I remove them so I've done so in this change.

**Comment by windo** [comment]
I tried also enabling the [indent](https://eslint.org/docs/rules/indent) rule, but it was tripping up on a few dozen locations where I guess it wasn't agreeing with what vim had considered to be "normal" indentation. I expect it might be possible to configure it a bit to make it work though.

**Comment by wonderingabout** [comment]
@windo 

these are used in the UHMAEAT (code managing maintime and periodtime rejects), current version 2.2

i dont know what changes the `eslint` are, but it looks a good thing :+1: 

however if we remove the UHMAEAT define variables, i think we will have undefined error later on in all maintime and periodtime rejects

our modern code has defaults, so can you just try to send a few game challenges above or below limits (for a example a live game with 4 hour byoyomi maintime, and see if the code works as intended)

i really dont know what changes you are doing, maybe they are good :+1: 
so just try and see if it still works

**Comment by windo** [comment]
I can't see how [universalMaintime](https://github.com/online-go/gtp2ogs/blob/673d4531797f2a4c0ce45e6d62588a73ef52b01f/connection.js#L580) is used in the code. The reject messages still seem to work when I try this change on the beta server.

**Comment by wonderingabout** [comment]
oh i see, now properties are linked to the main object, so `universalMaintime` local object is not needed anymore :+1: 

is it safe to leave duplicate names for maintimes and periodtimes rejects ? (just a beginner question, i guess it should be fine)

and finally can we comment out the notes on properties rather than deleting them ? @windo 

```	
/* maintime rejects properties table : 
                MinimumMaximumSentence : "",        // minimum/maximum	
                TimecontrolSentence : "",           // main time - initial time and/or max time, etc..	
                SpeedSentence : "",                 // for blitz , live , and corr	
                RankedUnrankedGamesIs : "",         // +/- ranked/unranked games is	
                TimeNumber : 0,                     // for example 600 (600 seconds)	
                TimeToString : "",                  // for example "10 minutes"  = timespanToDisplayString(config.xxx)	
                TimeNotificationToString : "",      // for example user wants "1 seconds" = timespanToDisplayString(t.xxx)	
                IncreaseDecreaseSentence : "",      // , please increase/decrease	
                                                    // main time - MaintimeTimecontrolSentence again	
                EndingSentence : "",                // optionnal, for example in canadian, adds explanation	
                ConnBelowAboveSentence : "",        // for conn_log : below/above	
                ConnSentence : "",                  // for conn_log sentence	
                TimecontrolString : "",             /*"fischer" , "simple", "byoyomi" , "canadian" , "absolute"*/	
                SpeedString : "",                   /* "blitz" , "live" , "corr" */	
*/
```

**Comment by windo** [comment]
Sure, I can do something like that.

**Comment by windo** [comment]
Transformed the object initializations into comment blocks, please take a look!

**Comment by wonderingabout** [comment]
@windo 

good :+1:  :100: 

but you could do even better (just one `/*` then `*/` , i should add this enhancement for all many lines comments in UHMAEAT 2.3 in another time commit) : 

and finally, this line 
```
            // The parts that the final message comprises of:
```

i would remove that and include something else inside the big `/*` to `*/`
because this line is not exactly accurate : some properties below are used as time numbers, or conn_log messages (but not reject messages to the user :rofl: )


result (feel free to copy paste)

for maintimes : 

```
            /* here is a list of all the properties used for maintime rejects : 
            MinimumMaximumSentence    - minimum/maximum
            TimecontrolSentence       - main time - initial time and/or max time, etc..
            SpeedSentence             - for blitz , live , and corr
            RankedUnrankedGamesIs     - +/- ranked/unranked games is
            TimeNumber                - for example 600 (600 seconds)
            TimeToString              - for example "10 minutes"  = timespanToDisplayString(config.xxx)
            TimeNotificationToString  - for example user wants "1 seconds" = timespanToDisplayString(t.xxx)
            IncreaseDecreaseSentence  - , please increase/decrease
                                        main time - MaintimeTimecontrolSentence again
            EndingSentence            - optional, for example in canadian, adds explanation
            ConnBelowAboveSentence    - for conn_log : below/above
            ConnSentence              - for conn_log sentence
            TimecontrolString         - "fischer" , "simple", "byoyomi" , "canadian" , "absolute"
            SpeedString               - "blitz" , "live" , "corr"
            */
``` 

for periodtimes : 

```
            /* here is a list of all the properties used for periodtime rejects : 
            MinimumMaximumSentence   - minimum/maximum
            TimecontrolSentence      - period time, period time for X stones, increment time, etc..
            SpeedSentence            - for blitz , live , and corr
            RankedUnrankedGamesIs    - +/- ranked/unranked games is
            TimeNumber               - for example 600 (600 seconds)
            TimeToString             - for example "10 minutes"  = timespanToDisplayString(config.xxx)
            TimeNotificationToString - for example user wants "1 seconds" = timespanToDisplayString(t.xxx)
            IncreaseDecreaseSentence - , please increase/decrease
                                       period time - PeriodtimeTimecontrolSentence again
            EndingSentence           - optional, for example in canadian, adds explanation
            ConnBelowAboveSentence   - for conn_log : below/above
            ConnSentence             - for conn_log sentence
            TimecontrolString        - "fischer" , "simple", "byoyomi" , "canadian" , "absolute"*/
            SpeedString              - "blitz" , "live" , "corr"
            */
```

thank you as always @windo :1st_place_medal: :+1:

**Comment by wonderingabout** [comment]
also i just noticed something else

in canadian the EndingSentence adds an explanation only for period time, not for maintimes ! 

let me edit my above code :+1:

**Comment by wonderingabout** [comment]
just edited my code if you want to copy paste it @windo (and version bump UHMAEAT to 2.3, you can mark that in commit notes if its ok to you :+1: )

and as always feel free to tell me all comments or suggestions :+1:

**Comment by wonderingabout** [comment]
just finished the edits if you want to copy paste it @windo (and version bump UHMAEAT to 2.3, you can mark that in commit notes if its ok to you :+1: )

and as always feel free to tell me all comments or suggestions :+1:

**Comment by windo** [comment]
Thanks, done!

**Comment by wonderingabout** [comment]
thanks too ! :1st_place_medal:

**Comment by wonderingabout** [comment]
last thing i hope now is `2.3` here too

https://github.com/windo/gtp2ogs/blob/eslint/connection.js#L569
https://github.com/windo/gtp2ogs/blob/eslint/connection.js#L977
https://github.com/windo/gtp2ogs/blob/eslint/connection.js#L978
https://github.com/windo/gtp2ogs/blob/eslint/connection.js#L1011
https://github.com/windo/gtp2ogs/blob/eslint/connection.js#L1012
https://github.com/windo/gtp2ogs/blob/eslint/connection.js#L1534
https://github.com/windo/gtp2ogs/blob/eslint/connection.js#L1535

the `//` is not needed, we can just skip a line here  :

for :  
https://github.com/windo/gtp2ogs/blob/eslint/connection.js#L580
https://github.com/windo/gtp2ogs/blob/eslint/connection.js#L1023

(same as in https://github.com/windo/gtp2ogs/blob/eslint/connection.js#L577)

hopefully it will be good after that :+1: 
i know the code is still a bit repetitive, sorry about that lol :+1:

**Comment by windo** [comment]
Should be all fixed, thanks for your patience!

BTW, I think you can click on the little "+" sign when you hover over the a code line (if you're looking at the changes in context of the PR from the github UI) so that you can leave the comments per-line. I think that makes it easier both the reviewer to leave the comment and for the reviewee (is that a word?) to see the comment in context.

**Comment by wonderingabout** [comment]
@windo 

welcome, i'm the one thanking you for your patience to rebase everytime lol :1st_place_medal: 

ok, i saw people use it to review but i'll try it next time :100:

**Pull request merged**
