### PR TITLE
add "Waiting for opponent to place all handicap stones" message + minor fixes of warning messages

### LINKED ISSUE #80: Chinese handicap : "waiting for you to play all your handicap stones" message
@roy7 @ anoek 
i noticed several players dont realize they have to play all the handicap stones when the game starts

after they play one stone, they wait a long time, and sometimes they even leave the game

it would be good to add a bot message during the game telling the player that more stones need to be added

for `n` handicap stones, at every `x` number of handicap stone played

```
"you put x handicap stones, please put n-x more handicap stones"
```
example for a 6 handicap stones game: 

```
"you put 1 handicap stones, please put 5 more handicap stones"
```

something based on if and else :)

my most recent example, this player https://online-go.com/game/15885917 waited like 3 minutes before playing his 2nd handicap stone

### PR DESCRIPTION
**Pull request by wonderingabout**
this fixes #80 
this is a small addition to @lemonsqueeze and @windo 's combined awesome and great work :+1: 
i want to apologize for the quite narrow minded position i had at that time in #96   :+1: 

better if once

also adds minor fixes and improvements to warning messages

@roy7 @Dorus

### CODE REVIEW

**Comment by wonderingabout** [comment]
update : maybe sending this message once is enough ?

**Comment by wonderingabout** [comment]
just rebased for cleaner commits

**Comment by windo** [comment]
I think 73b2da3 accidentally removed a closing brace after the `Warning: No min periods setting detected, games are likely to timeout` message.

**Comment by roy7** [comment]
Sorry for missing that. Fixed in https://github.com/online-go/gtp2ogs/commit/6e780eb2834cd6292bf86661fdfec052cd659472

**Comment by wonderingabout** [comment]
good catch @windo !

i made many changes and tested several times, so i assumed it was good, should have tested one last time :+1: 

i generally always test my branches and make some screenshots to compensate from my lack of experience, this one was careless, ty again everyone :+1:

**Comment by windo** [comment]
I do tat sort of thing all the time too. I have a branch that works well and then I "just fix one more thing" and forget to test. This is where that travis-ci integration would help, I think it can tell you when tests fail for a PR?

**Comment by wonderingabout** [comment]
@windo 
i never used travis but it sounds interesting
i'm looking forward to it :+1:

**Comment by roy7** [comment]
Travis is turned on, although it isn't something I know how to configure.

**Comment by windo** [comment]
@anoek, @roy7, when I go to travis, it does not seem to consider itself turned on:

https://travis-ci.org/online-go/gtp2ogs

I believe building all PR is enabled by default by travis.

**Comment by wonderingabout** [comment]
this looks so nice, looking forward to more :+1:

**Comment by roy7** [comment]
I don't have enough access rights to turn it on.

**Pull request merged**
