### PR TITLE
now using plurals for --bans --boardsizes --komis --speeds --timecontrols and co

### PR DESCRIPTION
**Pull request by wonderingabout**
@roy7 @Dorus @windo 

this PR is on top of #164 (now #173 )

see commit message for details :+1: 
didnt test it, i hope it works

### CODE REVIEW

**Comment by roy7** [comment]
Hmm not sure how I feel about plurals. I think normally command line options that take "1 or more" arguments normally use the singular?

"All checks failed" btw. If you click Details next to the "continuous" line you can see the error messages.

**Comment by wonderingabout** [comment]
@roy7 

this idea was suggested to me by @Dorus, and i think it makes sense, but maybe @Dorus can explain why

also, the fix in travis is easy 

```
config.allowed_sizes[19] = true;
```

need to be 

```
config.allowed_boardsizes[19] = true;
```

typo, will fix and check other remaining :+1:

**Comment by wonderingabout** [comment]
actually i didnt do any mistake, its just that i didnt update test.js :smile: 

https://github.com/wonderingabout/gtp2ogs/blob/plurals-bans-boardsizes-komis-speeds-timecontrols/test/test.js#L18-L21

**Comment by wonderingabout** [comment]
just did git merge from latest devel 

now the question is what do we want to do with this @roy7 @Dorus @windo 

didnt test it yet, but i hope it works (since the test.js includes a boardsizes 19 end to end game)

**Comment by roy7** [comment]
Are you running this live on your own bot? There's soo many lines with renamed variables. :)

**Comment by wonderingabout** [comment]
didnt test it yet @roy7 :smile: 

but i saw the test.js includes an end to end game test, so it should work

however, to make sure i'll test it first and tell you how it goes :+1:

**Comment by roy7** [comment]
I appreciate it. I'm personally not a fan of just renaming things for its own sake all over the place but if you and @Dorus want it that's fine.

**Comment by wonderingabout** [comment]
maybe we want to hear @Dorus 's thoughts on this again so we can have common agreement and understanding on this before making decision

to me, it looks natural to use plural since these plural families work the same way as arrays (they contain many values)

**Comment by wonderingabout** [comment]
as for me its just an idea i had without much knowledge behind it

**Comment by wonderingabout** [comment]
@roy7 

i'm very happy !!!

tested this : `--persist --noclock --komis 7.5,automatic --boardsizes 15,19 --speeds blitz,live --timecontrols byoyomi,fischer --minperiodsblitz 5 --minperiodslive 5 --minperiodscorr 5`

it all worked well at first try !! :smile: 
i'm so happy that now i am able to code things at first try without even testing them !!

thank you everyone for the review and always helpful advice !!!

@Dorus said on discord that he'll review this PR too, but it works as it is

also, maybe @windo has thoughts on it too ?

**Comment by Dorus** [comment]
@roy7 Yeah i prefer proper names, and the reasoning here is that if we even want to rename these things, we better do it now before a mayor release with these params is made.

For the historical picture: I told meta in another Pr to use plural variable names for arrays. He extended that to a lot of other places, including command line params. Tbh i must say i kinda like these names.

**Comment by wonderingabout** [comment]
@Dorus the only one that i find a bit weird is `--komisranked` for example, which may be read as "komi is ranked - is komi ranked"

but we'll get used to these eventually, and yes i also think its the good time to polish things before a major release

for same reasons, i plan to replace `let i of` with `let e of` after this is merged

then, `--colorseven` and `--colorshandicap` will use the same reasoning : "allowed" families get plural because they work like arrays :+1:

**Comment by roy7** [comment]
@windo If you have no objection to this overhaul I'll get it merged. Thanks all.

**Comment by wonderingabout** [comment]
thanks to you to @roy7 as always :1st_place_medal: :100: :1234: :+1:

**Comment by roy7** [comment]
Ok merging. Lets hope nothing else breaks. ;)

**Comment by wonderingabout** [comment]
thanks, this one was tested so i'm confident about it :+1:

**Pull request merged**
