### PR TITLE
add --bantimeouterssession --bantimeouterssessionranked --bantimeouterssessionunranked

### PR DESCRIPTION
**Pull request by wonderingabout**
edit: did not test it yet
initial simple implementation for now

### CODE REVIEW

**Comment by Dorus** [comment]
I tested this and it works. Ready when meta say it's ready,

**Comment by wonderingabout** [comment]
before merging this i need to:
- add unit testing
- decide if we want to consider a timeouter is a timeouter, or a timeouter in an unranked game is not a ranked game timeouter

**Comment by wonderingabout** [comment]
added unit testing and renamed to shorter option name, also added suggestion sentence for ranked unranked ("You may try unranked")

we may review this one last time to make sure all is good, and perhaps retest it too when review is finished

also, i intend to add a ban timeouters option based on a ban duration (ex: ban timeouter for 1 hour), but this would be in another pr

**Comment by wonderingabout** [comment]
there could be a simpler approach to this

we can see the timeout info on ui_class

if it is not in notification, then it is also visible in HTTP GET:

for example
https://online-go.com/termination-api/players?ids=434218

`[{"id":434218,"country":"_Pirate","username":"DarkGo","icon-url":"https://b0c2ddc39d13e1c0ddad-93a52a5bc9e7cc06050c1a999beb3694.ssl.cf1.rackcdn.com/3b8772d1ead443410d3bef349e75300f-32.png","ui_class":"bot timeout","ratings":{"overall":{"deviation":73.14,"rating":2498.01,"volatility":0.063192,"games_played":61741}},"rating":1470.594,"ranking":23,"pro":0,"online":1}]`

in `"ui_class":"bot timeout"`

sending a challenge to DarkGo from our bot would tell us if notification successfully gets the timeout info on its ui_class

**Comment by wonderingabout** [comment]
considering ui_class already tells us if user timed out recently from any game, not just in this session, it could be easier to just ask from ui_class, as explained in #348

**Pull request closed without merging**
