### PR TITLE
fix missing files pv.js and utils/** in package.json files for npm install

### PR DESCRIPTION
**Pull request by wonderingabout**
edit: this is also done in #333 where we also add constants.js to list of gtp2ogs files

quesiton:
should we also add .js test files here? (test.js and checkChallenge.test.js)

### CODE REVIEW

**Comment by Dorus** [comment]
Yes we need this. Good find!!

We messed up our gtp2ogs release royally, so stupid nobody complained about this so far :(

Please also add `utils/**` to this list.

**Comment by wonderingabout** [comment]
sure, i guess it would be good to make a new release, either 6.0.1 or 6.1.0 i guess

so i just add `utils/**` ?

**Comment by Dorus** [comment]
6.0.1 so it's easy to update for people.

Actually we might need to decide. Did we deprecate any command line option since the last release? If so we might want 6.1.0. In that case we could somewhat decide to also fork the old 6.0.0 release, fix the pv file and other missing files, and release bot 6.0.1 and 6.1.0 later.

**Comment by wonderingabout** [comment]
i just committed the fix

for version name we didnt much commits since 6.0.0, we dropped fakerank but it's a thing none was using as far as i know, the rest is minor ;)

https://github.com/online-go/gtp2ogs/compare/6.0.0...devel

**Comment by wonderingabout** [comment]
the suggestion to fork 6.0.0 seems a bit overkill, it's been only a few weeks since 6.0.0 release, and few people use gtp2ogs in general, so we may just drop support for old version and just release a bugfix 6.0.1 :thinking:

**Comment by Dorus** [comment]
Thinking about this for 5 more seconds, yes 6.1.0 makes zero sense as the current 6.0.0 release is so broken we have zero reason to care about compatibility. We can just wack on 6.0.1 with any number of updates and fixes :)

**Comment by Dorus** [comment]
@wonderingabout We should increase version number in this pr, or, we could close this one, increase version number in #342 since that one has everything this one has too.

**Comment by wonderingabout** [comment]
> Thinking about this for 5 more seconds, yes 6.1.0 makes zero sense as the current 6.0.0 release is so broken we have zero reason to care about compatibility. We can just wack on 6.0.1 with any number of updates and fixes :)

yes i agree!! :medal_military: 



> Thinking about this for 5 more seconds, yes 6.1.0 makes zero sense as the current 6.0.0 release is so broken we have zero reason to care about compatibility. We can just wack on 6.0.1 with any number of updates and fixes :)

yes i agree!! :medal_military: 

> @wonderingabout We should increase version number in this pr, or, we could close this one, increase version number in #342 since that one has everything this one has too.

if we merge 642 latyer, then we can increase it there
i like that this pr commits specifically the fix, it's a good way to highlight that there was an issue

**Comment by wonderingabout** [comment]
ah nvm it adds complications to merge this lol, better close it

**Pull request closed without merging**
