### PR TITLE
Removing ISSA (smart and short aliases), upgrade UHMAEAT from 1.0 to 2.2 (maintimes and periodtimes rejects)

### PR DESCRIPTION
**Pull request by wonderingabout**
general look here : https://github.com/wonderingabout/gtp2ogs/tree/no-ISSA--UHMEAT-2-2

2 main changes here : 

1- removing ISSA (intuitive semi-syllabic aliases) : 
we plan to use config file in the future, so not needing these anymore, as convenient as they may have been in the past, a config file will avoid for bot admin the need to input anything anymore, read commit message for details

2A- supported "none" and "absolute" again, but not in defaults : 
later, we plan to add "none" and "absolute" to the defaults of the soon coming and already coded by me ---timecontrolunranked gtp2ogs argument
for absolute, the reason it is removed from defaults is because with default blitz and live maintimes, the games would end in just 1 or 2 moves, so not possible with default minimum values, see UHMAEATs changes below for details

2B- upgrading UHMAEATs for maintimes and periodtimes from 1.0 to 2.2
read commit change and code for details
but basically the main idea motivating this is that for example --maxmaintime 7200 (2 hours) default would make correspondence games impossible to accept
so now the UHMAEAT 2.2 adds `--min*max/maintime/blitz*live*corr/+-ranked*unranked` options, and same for periodtimes

3- minor
removing a few code duplicates

UHMAEAT 2.2 also brings many code optimizations even though functionnally being almost the same for end user, read commit message and code for details

@Dorus @roy7 @anoek 

see #124 and #129 for screenshots

please also test it before merging, i did extensive testing, but it is so that you can make sure i didnt miss something

--minmaintimeblitz
--minmaintimeblitzranked
--minmaintimeblitzunranked
--maxmaintimeblitz
--maxmaintimeblitzranked
--maxmaintimeblitzunranked

--minmaintimelive
--minmaintimeliveranked
--minmaintimeliveunranked
--maxmaintimelive
--maxmaintimeliveranked
--maxmaintimeliveunranked

--minmaintimecorr
--minmaintimecorrranked
--minmaintimecorrunranked
--maxmaintimecorr
--maxmaintimecorrranked
--maxmaintimecorrunranked

### CODE REVIEW

**Comment by wonderingabout** [comment]
update : 

while rereading, noticed we now have a duplicate of

!config.allowed_timecontrols[t.time_control]

its ok, will be clearer in my next PR, and doesnt prevent our current code from running

and after all, there is a duplicate of boardsize too, but all this will be taken care of in the next commits (already coded)

**Comment by anoek** [comment]
Good commit message 😃

**Comment by wonderingabout** [comment]
thank you @anoek , i really appreciate and want to apologize again for my sensitivity when it comes down to my pride :+1: 

if there is anything that can be improved in the future, please dont hesitate to point it :+1:

**Comment by roy7** [comment]
Ok since all of this is related to messages back to people trying to challenge bots, and just the aliases which were only in devel briefly anyway, I'm going to get it merged. Plus I know @wonderingabout has been using it in live operation since he wrote it.

If there is some subtle error someplace, it should show up quickly enough and only impact challenge replies or acceptance, not messing up a bot mid-game.

**Comment by wonderingabout** [comment]
ty @roy7 

i submitted some screenshots in #129 and #124 

now that this is merged, i'll submit the next chunk : boardsize display enhance, komi display enhance, boardsizeranked and co, komiranked and co, speedranked and co, timecontrolranked and co, adding "family_guard" to "allowed_" see next incoming PR for details as this last point is easier understood when seen

**Pull request merged**
