### PR TITLE
minor komi notes : round 2

### PR DESCRIPTION
**Pull request by wonderingabout**
some careless `` forgot to be taken care of :) :laughing: 

i hope you'll bear with my unexperience and high maintainence lol @roy7 

thanks again for your efforts everyone, let's make OGS more awesome :1st_place_medal:

### CODE REVIEW

**Comment by wonderingabout** [comment]
hmm

for some reason notes a link doesnt want to work (b c d e work though)

i'll investigate why

general look here
https://github.com/wonderingabout/gtp2ogs/tree/custom-boardsize-width-height

**Comment by roy7** [comment]
Ok so let me know when it's ready to merge.

**Comment by wonderingabout** [comment]
ok :)

**Comment by wonderingabout** [comment]
this is seriously weird lol

links for b c d work, exact same thing copy pasted, but a doesnt work :)

**Comment by wonderingabout** [comment]
phew this was funny lol

fixed now :) 

https://github.com/wonderingabout/gtp2ogs/blob/custom-boardsize-width-height/README.md#a-

you can merge @roy7  :1st_place_medal:

**Pull request merged**
