### PR TITLE
Delete gamedata.clock.now before processing gamedata packets

### PR DESCRIPTION
**Pull request by roy7**
This is to solve https://github.com/online-go/gtp2ogs/issues/294.

### CODE REVIEW

**Comment by wonderingabout** [comment]
maybe remove the commented-out line or comment something about it too?
https://github.com/online-go/gtp2ogs/blob/devel/bot.js#L188

**Comment by roy7** [comment]
Since we don't update gamedata.clock from clock events, the commented out code is actually completely separate. I wrongly assumed we updated gamedata.clock when a clock event arrived. Oops. :) We could remove it since it's old and commented out but it's actually unrelated.

**Comment by wonderingabout** [comment]
yes :)

i'll test this code for one week or something and tell you if i find any issue (can send all my logs at the end of the week ;)

testing branch is:
https://github.com/wonderingabout/gtp2ogs/tree/rejectnewtime-v2

**Comment by wonderingabout** [comment]
similarly to this issue, it may also be a good idea to keep track of notifications we receive in debug because we never know if we don't receive any unexpected element from server
i am testing this in #295

**Comment by wonderingabout** [comment]
i got a few clock.now elements errors again this hour, even though there was no more crashloop

see full log:
 # [Download Full Log (2.1 MB)](https://drive.google.com/file/d/1xZjlsrEIK-1laXjwwj5zwLOEwVQsQWnw/view?usp=sharing)

also i got 502 gateway errors on discord, various chromium websites, etc, so its possible few internet shortages and/or instability are involved in tonight's issue

**Comment by wonderingabout** [comment]
this is from today's log (7748 and 7849)

clock.now is the only difference:

gamedata error again

**Comment by roy7** [comment]
Oh I'm dumb. We don't store this.state.gamedata. this.state IS gamedata. So when we update this.state.clock we're changing our internal gamedata, and thus this.state.clock.now will appear from clock events after all.

**Comment by wonderingabout** [comment]
great :smiley: 
i'll add your new change and continue the testing :1st_place_medal: 

and being dumb is a great quality for being a developer ;)

also i suggest we rapidly merge this if it doesnt break anything, it's a major achievement just on its own, and we can add further fixes later :)

**Pull request merged**
