### PR TITLE
Big to small PR part2

### PR DESCRIPTION
**Pull request by wonderingabout**
general look here : https://github.com/wonderingabout/gtp2ogs/tree/bigToSmallPR-Part2

easy review here : https://github.com/online-go/gtp2ogs/pull/133/files?utf8=%E2%9C%93&diff=split

phew it was surprisingly easy to merge conflicts lol (no error !! all automated)

back to issues now, here is a quick summary : 

continuation of PR #130 , 

read changelog in #124 and #129 

@Dorus @roy7

### CODE REVIEW

**Comment by wonderingabout** [comment]
oh and dont spend too much time with the UHMAEATs 2.0, they work as they are, and later i released UHMAEAT 2.1 and 2.2, so dont bother with it as long as it just works

**Comment by anoek** [comment]
This title is not any better, and the description is not useful.

Please take a look at other commits and pull requests, please make the title a clear and concise summary of what is in the PR. Please fill the description in with further expanded details. Avoid being cute or funny, just keep it nice and boring. Please avoid made up acronyms, at least not without an explanation as to what they are.

**Comment by wonderingabout** [comment]
sorry for not being good enough, what can i say

**Comment by anoek** [comment]
No problem, we all start off there :) Next PR just try and put yourself in the shoes of others that are going to be reviewing and checking out your code.

**Comment by wonderingabout** [comment]
i'll be happy to listen to other people's wishes when mine are replied to

**Comment by wonderingabout** [comment]
if you dont know what i'm talking about, ask other moderators about the gnugo issue

**Comment by wonderingabout** [comment]
@anoek 

if you want to clarify your words in a way i can understand it more clearly, please do

if you dont, i'll just take you to your word thats just an all subtle and ironical criticism

but i doubt i'm mistaken here

**Comment by wonderingabout** [comment]
as expected, you really mean it in an ironical way @anoek 

you have mail notifications, so if you're not answering its on purpose

i'll wait as long as needed for you to clarify if you want

but if you dont want to clarify your words, then i'll just take your 2 above comments here as subtly insulting me while pretending to help

**Comment by roy7** [comment]
@anoek Sorry about that, we're trying to take his huge PR from the other day and break it into chunks to get it all merged one smaller but still large piece at a time.

**Comment by anoek** [comment]
For what it's worth it's not my intention to insult or ignore, it's Sunday morning and I have kids, I grab moments when I can to respond.

I don't mean my feedback as insulting, I mean it as giving feedback as to what would be helpful for you to do to help get your commits pushed through. This applies to pretty much any project you're committing code to, not just ours. I'm sorry if it comes off brusque, I just want to be clear and I don't like to mince words. PR's should be small, focusing on one thing ideally, the titles should clearly outline what the PR is about, and the description should provide any further details reviewers should be aware of. Make it easy for them understand what's going on before they delve into your code, you'll find your PRs get pushed through the pipeline much quicker that way.

And I'm sorry if I'm messing things up @roy7 , this has been your project for awhile now and I'll drop out of the comment chain if you'd rather.

**Comment by wonderingabout** [comment]
@anoek thanks for your reply

i totally agree with you that my commits are bad and all, and indeed they should be improved

however what i didnt like is that i just felt that you didnt try to criticize my code or commits but rather criticize me as a person, and i couldnt help but to feel that you purposely disrespected me, i hope you understand that now

since it seems i was mistaken, i am now apologizing for that

however i would also like you to read yourself again and tell me if you find it a respectable answer

again, i 100% agree that the code may be bad, and i am totally open to it just being rejected

i was just talking about the how, not the what

**please next time take time to write your answers in a clear way that may not be misunderstood by the person you speak with, and if you cant do that (no time, not want, etc...), then please dont answer, this is better than doing harm intentionnally or not**

i really felt personally insulted, not my PR here, so when i feel a bit better i'll resubmit it again

again, i welcome all criticisim so please dont hold back, but dont say it in an unclear way, and please clear any misunderstanding as fast as possible

only asking to be respected, thanks

**Comment by wonderingabout** [comment]
please dont hold back on the criticism
but do it in a respectful way, thats all i ask

thanks

**Comment by roy7** [comment]
@anoek Please don't disappear on us. :) But I'll shoulder getting all of this stuff from that huge PR the other day merged eventually and future PRs should be more concise and easy for anyone to review/merge. Some other things like windo's questions on chat authentication I can't possibly answer for him.

**Comment by wonderingabout** [comment]
if you apologize for being unclear and unintentionnally upsetting me, i would not dislike it too @anoek 

hopefully that would close this issue

**Comment by anoek** [comment]
I apologize for being unclear and unintentionally insulting and upsetting you.

For the record I was not commenting at all on the quality of your code, I was only trying to point out (in an asshole way apparently) what would make it easier for reviewers to review your PR.

**Comment by wonderingabout** [comment]
@anoek i am very thankful for your apology and i can accept it

i hope you can also accept my apology for making a ruckus now

i can understand what you meant now @anoek 

however, i hope you can also understand now how i could misunderstand it and take it personally

in the future, please dont hold back and criticize me as much as needed, i would find it disrespectful if you held back on that

however please do it in a clear way that may not be misunderstood

thanks again, i hope we can move on from here

**Comment by wonderingabout** [comment]
also as @roy7 said we're really short on contributors and it is only because you started all this that we can be here today, so if we could have one more knowledgeable contributor, i would certainly be thankful of that and appreciate it

**Comment by wonderingabout** [comment]
that closes it now as for me, sorry for the commotion

**Comment by anoek** [comment]
Cheers, and yeah I could have certainly said things better looking over things.. I do try, but fail often, at things like this. I will continue to strive to do better though :)

**Comment by wonderingabout** [comment]
its ok, as long as you and me try to care about each other, i'm sure the result will be satisfying in the end

i hope i can learn from what happened today too :+1: 

well then, looking forward to things too, thanks again :+1: 

i'll redo my PR from scratch, please dont hesitate to point any thing that can and/or should be improved @anoek

**Pull request closed without merging**
