### PR TITLE
Reject by time

### PR DESCRIPTION
**Pull request by Dorus**
In competition with pr #289 (rejectnewthreshold) this will allow bot admins to reject games between certain times.

### CODE REVIEW

**Comment by Dorus** [comment]
One todo here is to hide the bot when reject time is active.

**Comment by wonderingabout** [comment]
> One todo here is to hide the bot when reject time is active.

@roy7 did it here :sweat_smile:

**Comment by wonderingabout** [comment]
if we merge #332 this should be updated to match check_rejectnew being a local function in connection.js in this commit https://github.com/online-go/gtp2ogs/pull/332/commits/bbc7adbf91e0dc79731271bfad301c43e81a5333

**Comment by roy7** [comment]
@Dorus #289 was closed. Do you want to fix conflicts to get it merged, leave it for now, or close it?

**Comment by Dorus** [comment]
I would have to dig into this change set, rebase it and see if it's complete. I'll do that soon and decide then.

**Comment by anoek** [comment]
Feel free to re-open this if you decide to pick it back up

**Comment by Dorus** [comment]
Ah yes, this completely fell off my radar. Will reopen if i ever finish it.

**Pull request closed without merging**
