### PR TITLE
upgrade old dependencies in package.json

### PR DESCRIPTION
**Pull request by wonderingabout**

### CODE REVIEW

**Comment by wonderingabout** [comment]
i tested on beta ogs and a game works end to end!!!

**Comment by wonderingabout** [comment]
i also tested writing tests with the new mocha and sinon and it works too successfully

writing a text with unexpected results is tested error successfully, and writing a valid test is tested pass successfully

i dont know why package.lock-json suddenly got so large after upgrading mocha and sinon

**Comment by wonderingabout** [comment]
after all these upgrades the number of audits has been reduced

from 52 (2 high, 50 low) (current latest devel, with yargs included)

audit of current devel


to 44 (44 low)

current npm audit

**Comment by wonderingabout** [comment]
it seems only lodash package is creating all these 44 vulnerabilities (even though i know nothing about these (but want to learn :smile: ))

i linked `npm audit` result:
https://pastebin.com/UwKvqbWn

**Comment by Dorus** [comment]
Yes we can merge this.

**Pull request merged**
