### PR TITLE
Update README.md (--hidden and --rejectnewfile)

### PR DESCRIPTION
**Pull request by TokumotoK**
Please pull this AFTER pulling the --rejectnewfile update.

### CODE REVIEW

**Comment by roy7** [comment]
This pull request changes about 2000 lines of code in gto2ogs.js. I can't image that is intentional? Could you make a request just for your README changes?

**Comment by TokumotoK** [comment]
Uggghhh owwww...   It said No Conflict to me...

Could you pull README.md from https://github.com/TokumotoK/devel/README.md ?

**Comment by roy7** [comment]
No conflict just means all of your changes could be applied. But you are submitting the PR off of what I assume is a highly customized version of gtp2ogs and not the base version.

If you have a branch in your fork to track the main server, you'd want to checkout that, then make the new branch for the readme PR (so the starting point is identical to server), then do the PR. Once the readme PR is merged, you could then pull your local server branch into your custom branch to update your custom branch.

Regardless I'll check tonight about just downloading the README manually into a new branch on my end and getting it merged that way.

**Comment by roy7** [comment]
Will do it now in fact.

**Comment by roy7** [comment]
https://github.com/online-go/gtp2ogs/pull/67 merged

**Pull request closed without merging**
