### PR TITLE
update package-lock.json to 6.0.1

### PR DESCRIPTION
**Pull request by wonderingabout**
removed node_modules folder then ran `npm i` from latest devel

edit: tested to work on beta, ready to merge

### CODE REVIEW

**Comment by Dorus** [comment]
Did you also run things like `npm audit fix` and update outdated packages? Might be a good thing to add here.

**Comment by wonderingabout** [comment]
ah i didnt do it because i dont know about these things, i'll try it! :100:

**Comment by Dorus** [comment]
Just make sure you test things still work after updating. Package-lock is made specifically to avoid breaking things because of random updates, but only update when developers request it so they can test if nothing randomly broke.

**Comment by wonderingabout** [comment]
this should be merged after #342 as it needs some testing before merging, and is independent from the other important changes

also we should merge this pr before making a new 6.0.1 release

**Comment by wonderingabout** [comment]
so far it looks like this, didnt run any audit yet

**Comment by wonderingabout** [comment]
should redo it properly lol in another pr

**Pull request closed without merging**
