### PR TITLE
move test pv output samples to /test/pv_samples

### PR DESCRIPTION
**Pull request by wonderingabout**

### CODE REVIEW

**Comment by Dorus** [comment]
But this is input not output.

**Comment by Dorus** [comment]
we decided to rename the folder pv_samples

Can be merged once that's done.

**Comment by wonderingabout** [comment]
i renamed it to pv_samples :)

**Comment by roy7** [comment]
Conflict needs fixed then I can merge

**Comment by wonderingabout** [comment]
@roy7 done :+1:

**Pull request merged**
