### PR TITLE
Minmaxhandicap family rejects function, which also includes handicaponly and evenonly specific rejects

### PR DESCRIPTION
**Pull request by wonderingabout**
@roy7 @Dorus @windo 

this PR is on top of #175 

now uses an interesting function for easier code maintainance
and cleaner code

didnt test it, but i hope it works :+1: 

this may be the starting stone for similar functions before master relase

### CODE REVIEW

**Comment by wonderingabout** [comment]
just rebased this in a smarter and more functionnal way :+1: 

didnt test it, i hope it works :+1:

**Comment by wonderingabout** [comment]
will rebase next time, tired for today lol, but it should work now

it was only an issue about the scope of `notification.handicap` being not defined in the original place where i put the function :+1:

**Comment by wonderingabout** [comment]
just rebased this, ready to merge @Dorus @roy7 

(didnt test it though, but i hope it works) :+1:

**Comment by roy7** [comment]
Maybe I just don't understand how it works.

There's a test like `if (!arg.includes("ranked"))` but we're calling it like `minmaxHandicapFamilyReject(config.minhandicap)` so 'arg' will be something like the number 4?

**Comment by wonderingabout** [comment]
@roy7 i dont understand what you dont understand :smile: 

its true that the `if (!arg.includes("ranked"))` test is redundant, i thought of removing it, then chose to keep it for clarity, but i may remove it in a further PR (there are way too much PRs that depend on this one, would have to rebase a lot)

**Comment by roy7** [comment]
The function calls need to be more like `minmaxHandicapFamilyReject( { "minhandicap": config.minhandicap } )` for this to do anything. @wonderingabout is working on fixing them. :)

**Comment by wonderingabout** [comment]
@roy7 

what is fun is that i did it like that for other functions in other PRs, but will do it here too i guess :+1: 
ty for help :+1:

**Comment by roy7** [comment]
Well if I merged broken stuff previously I hope we can relocate it and fix them.

**Comment by wonderingabout** [comment]
yes, but since the other PRs have the same problem, better redo it cleanly :smile:

**Pull request closed without merging**
