### PR TITLE
support place_free_handicap for placement

### PR DESCRIPTION
**Pull request by windo**
This is to resolve: https://github.com/online-go/gtp2ogs/issues/89

For now, it requires a commmand line flag --placefreehandicap to request the new behavior.

### CODE REVIEW

**Comment by windo** [comment]
I realized there was an earlier request for this:

https://github.com/online-go/gtp2ogs/issues/70

**Comment by wonderingabout** [comment]
great work @windo , big thanks !! :1st_place_medal: 

it is also related to this issue #80

**Comment by lemonsqueeze** [comment]
Hi,

Not sure i understand the new logic but maybe this is more complicated than it needs to be ?

Have a look at PR #96, looks fairly clean once makeMove() has been decoupled.

**Comment by roy7** [comment]
Similar changes handled via https://github.com/online-go/gtp2ogs/pull/96 instead.

**Pull request closed without merging**
