### PR TITLE
Handle bot crashes

### PR DESCRIPTION
**Pull request by windo**
Added some handling for various ways I could get gtp2ogs to observe the bot failing (I ran it with shell scripts that crash and fail in various ways). I added tests to follow what I saw subprocesses and OGS server do - but obviously they just aproximate the real behavior. I did test the new version against beta server too and am now running it on my bots without much runtime as of yet. 

I added a whitespace cleanup commit on top because it is (supposed to be) a NOP tiny cleanup. But I can open a separate PR for that if you'd prefer.

### CODE REVIEW

**Comment by wonderingabout** [comment]
i wonder if this code can restart phoenixgo after it crashes from a forked board, in #128 

still nice to add more features and enhancements @windo :+1:

**Comment by windo** [comment]
Oh, I updated the code but forgot to update the tests...

**Comment by windo** [comment]
@wonderingabout - it will try to restart the bot command 5 times so if one of those succeeds, then this PR should help.

**Comment by wonderingabout** [comment]
@windo 

if thats the case i'm sure it will help
because after i manually exit/restart gtp2ogs the game starts normally

can we add a sendchat (if not already present in this PR) ingame ?
" bot just crashed, restarting attempt 1/5, please wait"

**Comment by windo** [comment]
Sending something in the chat SGTM, though sending one message for each retry in case it is permanently failing for some reason might be too chatty. I think it makes sense to have each of the retries clearly visible on gtp2ogs logs but maybe only send a chat message when all 5 attempts to restart the bot have failed and we resign the game? Otherwise the user might be confused when the bot resigns at a strange moment in the game.

WDYT?

**Comment by wonderingabout** [comment]
depends, indeed once in ingame chat may be enough

in that case it would be more like : 

" bot just crashed, attempting a restart of the bot, please wait, will tell you the result shortly"

also no idea what SGTM means lol

**Comment by wonderingabout** [comment]
oooh and then add this  !!

it would be so sci-fi like loool : 

if success -> "bot restarted successfully, resuming the game from last position" // (after all we can crash later, not only at move 1"
if fail -> "bot failed to restart, decided course of action : resign, sorry for the disturbance, bot admin has been notified of this issue"

**Comment by windo** [comment]
I ran my bots on this branch and it caused a very large number of bot processes to be leaked and never be cleaned up, grinding the server to a halt. So definitely don't merge as-is, I'll have to find and fix that issue first :)

**Comment by windo** [comment]
I added some explicit kill() commands that seemed to do the trick. Running with a stable number of processes for my bots now.

**Comment by windo** [comment]
Removed the whitespace commit from this PR

**Comment by wonderingabout** [comment]
> I added some explicit kill() commands that seemed to do the trick. Running with a stable number of processes for my bots now.

looking forward to testing this when merged in devel (doing other things so not testing it now) :1st_place_medal: 

@windo big thanks for this nice add

i hope it will address the phoenixgo crash issue (and, actually even leela zero crashes sometimes too, so we all benefit it :+1: )

**Comment by wonderingabout** [comment]
i'd like to add some sendchats, for example here : https://github.com/online-go/gtp2ogs/pull/131/files#diff-41c4530a42496f695607188d7bbe06d5R251

same text message than log, but ingame sendchat it too

**Comment by roy7** [comment]
The conflict seems to be just whitespace related except for the one line about SendPass which I'm unsure why that's happened or what may have changed related to it. Hopefully my prior PR didn't break something in this section of the code?

**Comment by roy7** [comment]
Hey you know what's hot, with your changes to command() to support callbacks, after this is merged we could add a feature for initial bot startup to calculate and send the time info to the bot after one of the basic startup commands is completed (like "komi" or whatever). This way the bot has accurate time left and not "losing" the time between startup and seeing the time_left command. Might eliminate need for startup buffer per https://github.com/online-go/gtp2ogs/issues/107/.

I don't see an easy/obvious place to put such a thing though. But the idea is we'd want to have a pause in node processing between "launch the bot" and "bot is ready to play" so time_left and so on is generated and supplied after bot is ready for input.

Perhaps we'd do inside loadClock() by sending time_settings normally, but calculate time left and send time_left in the callback after time_settings is processed. Some tricks in how we handle time_left for game modes like Fischer would need closely examined.

Or perhaps more generally bot or game state should have a flag for "bot is ready", perhaps setting the value as a callback to the boardsize command() (the first we do in loadState(). So as soon as we get a response from the bot engine, we know it's ready for commands. Where we'd check this is when we are going to call loadClock() inside getMoves(). Actually for simplicity, I think in game.js in gotBotMoves() we could look at where we call this.bot.getMoves().

If (this.bot.botisready) this.bot.getMoves() as usual.
Else, this.bot.command("list_commands") or similar with a callback to this.bot.getMoves().

Just brain storming here.

**Comment by roy7** [comment]
All of the stuff from wonderingabout is done now, so if you resolve any conflicts now we should be all set to merge this as well if you're ready. Thanks!

**Comment by windo** [comment]
Rebased. I've been running this branch for a few days now without obvious problems - though I don't think I've had a bot crash either so can't tell for sure that it's helping.

**Comment by roy7** [comment]
Would you be bored enough sometime to run a test game or two and kill the process mid-move to see if it goes smoothly? ;) Or try launching a game with invalid params to the bot so it'll try the 5 (?) restarts and then exit cleanly?

**Comment by windo** [comment]
I have tried launching various invalid bots but I have not tried killing a bot mid-game. I'll try that.

I also just got a game that got stuck, after a disconnection from server:

```
Feb 20 03:00:05   connection.js:1658             #  disconnectFromGame 16656005
Feb 20 03:00:05   connection.js:1658             #  Disconnected from server
Feb 20 03:00:05   bot.js:130                     [7038] Stopping bot
Feb 20 03:00:05   bot.js:130                     [7038] Attempting to send to dead bot: quit
Feb 20 03:00:05   game.js:472                    [Game 16656005]  Move 212  Disconnecting from game.
Feb 20 03:00:05   connection.js:1658             #  disconnectFromGame 16656255
Feb 20 03:00:05   bot.js:130                     [20673] Stopping bot
Feb 20 03:00:05   bot.js:130                     [20673] Attempting to send to dead bot: quit
Feb 20 03:00:05   game.js:472                    [Game 16656255]  Move 50   Disconnecting from game.
Feb 20 03:00:05   bot.js:130                     [7038] Bot exited
Feb 20 03:00:05   game.js:472                    [Game 16656005]  Move 212  We may need to move but were not able to. Re-connect to trigger action base
d on game state.
Feb 20 03:00:05   bot.js:130                     [20673] Bot exited
Feb 20 03:00:05   connection.js:1658             #  Connected
Feb 20 03:00:05   connection.js:1658             #  Bot is username: amybot-ddk
Feb 20 03:00:05   connection.js:1658             #  Bot is user id: 608184
```

That happened exactly in the middle of a `genmove` being pending, so I don't think it has to do with this change, just some sort of confusion WRT game state when reconnecting.

**Comment by windo** [comment]
Tested on beta server and killed bot both during my move and managed to kill it in the middle of genmove. In both cases, bot was restarted and it continued the game.

**Comment by roy7** [comment]
The server restarts now and then which can disconnect bots and/or send an extra gamedata packet which is why I restart bots when that happens. I believe Tuesday is the day anoek restarts the server for any new bug fixes/changes each week. So maybe 3am per your log was when the official server restart happened.

**Comment by windo** [comment]
I've seen a few more cases of server restarts getting games stuck now, will file as a separate issue.

**Comment by wonderingabout** [comment]
@windo 

i dont run my bot long enough to have such an issue, but this is great :1st_place_medal:

**Comment by roy7** [comment]
@windo Is this good to merge (ie: we're confident the hung bots you are seeing are not a result of these changes but something else)? I don't recall bots begin hung with the older gtp2ogs, but then again, if a gamedata never comes from server I'm at a loss how it wouldn't.

**Comment by windo** [comment]
Yes, I think the hung bots are due to the server reconnect issue.

**Pull request merged**
